### ISSUE TITLE
Container stops while creating a payload

### ISSUE THREAD

**Issue by HSIS007** [MythicAgents/hermes#1]
Hi, 

Hermes container stops while creating a payload and not sure what is causing the issue.

Regards
HSIS007

**Comment by gmatuz** [comment]
@HSIS007 waiting long enough (~10minutes) the first time you create a payload did the trick for me
you will be able to see the logs of the hermes container when the intial installation is done, after that it works like a charm

**Comment by slyd0g** [comment]
Hey @HSIS007, please let me know if ^ fixes your issue. The very first payload creation it takes 5-10 minutes to install Command Line Tools (necessary for payload creation). It appears that during this time the payload container seems to go down. I'm still looking for a better way to automate this process.

**Comment by slyd0g** [comment]
Just figured out a better process for this, once Hermes is updated for Mythic 2.3 this will no longer be an issue and you can instantly create payloads without waiting for Command Line Tools to be installed:

![image](https://user-images.githubusercontent.com/22451367/153728613-efafaf27-6eaa-4682-b676-534c61f6ea37.png)

**Comment by slyd0g** [comment]
This issue has been fixed as of the update to Mythic 2.3. I pre-install Command Line Tools within the Docker container now.
