### ISSUE TITLE
Need to update version of Darling linked to in the instructions

### ISSUE THREAD

**Issue by rolen** [MythicAgents/hermes#4]
Currently the version of Darling that is linked to in the installation instructions is marked ```DON'T USE. OUTDATED``` on the Darling project's release page. Might be better to link to the releases page anyway rather than to a specific build.

**Comment by slyd0g** [comment]
Thanks for raising this up! I'll make a note to try to use an updated version of Darling. I mainly did this because I was scared of version mismatches between Darling on the host and Darling within the container.

**Comment by slyd0g** [comment]
Will keep this open for now until I test updated versions of Darling.

**Comment by slyd0g** [comment]
Hi, this shouldn't be an issue anymore with the recent Mythic 3.0 update. Darling doesn't rely on the kernel module anymore and lives in userland now. Give it a try again!
