### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by origeljuan** [MythicAgents/hermes#5]
I have installed the .deb package along all of it's dependencies, after I install the "hermes" agent into Mythic, i do not see the agent as being installed, the docker is creating a container for hermes, but I cannot see it.  In my command prompt on my box I'm able to utilize the darling shell, unsure why i'm not seeing hermes.  I also attempted to install darling in the latest version of Ubuntu 22.04, and running into the same issue, all the other agents that I have installed show up with out an issue, but hermes is not after making sure that darling is running on the system and doing the modprobe command prior to starting the mythic c2 agent.  Thank you.

**Comment by sfc-gh-jubui** [comment]
Hi, this should be resolved with the Mythic 3.0 release I just pushed out as the kernel module is no longer needed!

**Comment by slyd0g** [comment]
Hi, this shouldn't be an issue anymore with the recent Mythic 3.0 update. Darling doesn't rely on the kernel module anymore and lives in userland now. Give it a try again!
